name: Code Quality Assurance - JavaScript/TypeScript

on:
    push:
        branches: [master]
        paths:
            - "**/*.js"
            - "**/*.json"
            - "**/*.ts"
            - ".github/workflows/code-qa-js.yaml"
            - "eslint.config.js"
            - "jest.config.js"
            - "package*.json"
            - "tsconfig*.json"
    pull_request:
        branches: [master]
        paths:
            - "**/*.js"
            - "**/*.json"
            - "**/*.ts"
            - ".github/workflows/code-qa-js.yaml"
            - "eslint.config.js"
            - "jest.config.js"
            - "package*.json"
            - "tsconfig*.json"

permissions:
    contents: read
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [24.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v7
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Cache Node.js modules
              uses: actions/cache@v6
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Check installs
              run: npm ci
            - name: Quality check - prettier
              run: npm run prettier:check
            - name: Quality check - eslint
              run: npm run eslint:check
            - name: Run Jest tests
              run: npm run test
            - name: Build check
              run: npm run build
